spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/myredis
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cache: trace # Redis ??? ?? ??? ????? ??

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://instagram-db.cggfqax3smkr.ap-northeast-2.rds.amazonaws.com:3306/myredis
    username: admin
    password: password